### ISSUE TITLE
Bus stop encroach on zoning

### ISSUE THREAD

**Issue by Aspyro** [citiesskylines-csur/CSUR#6]
Bus stops created encroach on the zoning.

![IMG](https://user-images.githubusercontent.com/37420016/78450383-82c31000-767e-11ea-8811-f98dde5ae674.png)
![IMG2](https://user-images.githubusercontent.com/37420016/78450445-e4837a00-767e-11ea-9f98-b1e0705638da.png)

**Comment by victoriacity** [comment]
Position of the zoning grid is determined by the width of the road, when there is no bus stop present. The game does not change the zoning grid when a bus stop is placed on the road, so this is due to the limit of the game mechanics. Address this problem can be [suggested as a future feature of CSUR Toolbox](https://github.com/citiesskylines-csur/CSURToolBox/issues).
